### ISSUE TITLE
[Feature] 是时候把 modmanager的链接改到这里了？

### ISSUE THREAD

**Issue by shenjackyuanjie** [Forgot-Dream/modmanager-qt#1]
### What new features do you want? (你想要什么新功能)

一些原来modmanager的链接可以指向这里了吧

### This issue is unique (这个issue是唯一的)

- [X] I have searched the issue tracker and did not find an issue describing my request.

**Comment by Forgot-Dream** [comment]
只打算维护可用性，其他更改包括内容更新不进行考虑。
